


services:
  - type: redis
    name: prostaff-redis

    plan: free
    ipAllowList: [] # Access only from within Render

  - type: web
    name: prostaff-api
    runtime: docker

    plan: free
    dockerfilePath: ./Dockerfile.production
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://prostaffgg.netlify.app,http://localhost:5173

      - key: REDIS_URL
        fromService:
          type: redis
          name: prostaff-redis
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
